//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAKProtocolManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DBQueries : global::System.Configuration.ApplicationSettingsBase {
        
        private static DBQueries defaultInstance = ((DBQueries)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DBQueries())));
        
        public static DBQueries Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bd_isp")]
        public string DBName {
            get {
                return ((string)(this["DBName"]));
            }
            set {
                this["DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT ispytan.IspInd AS id, ispytan.IspData AS tested_at, CONCAT(cables.CabName,' ',cables.CabNameStruct) AS cable_name, cables.StrLengt AS build_length, cables.CabNum AS cable_id, barabany.barabanNum AS baraban_number, ispytan.CabelLengt AS cable_length, ispytan.Brutto AS brutto FROM ispytan LEFT JOIN cables USING(cabNum) LEFT JOIN barabany USING(barabanInd) WHERE ispytan.IspData >= '{0}' AND ispytan.IspData <= '{1}'")]
        public string SelectTestsList {
            get {
                return ((string)(this["SelectTestsList"]));
            }
            set {
                this["SelectTestsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" SELECT MAX(IspData) AS max_date, MIN(IspData) AS min_date FROM ispytan")]
        public string MinMaxDateQuery {
            get {
                return ((string)(this["MinMaxDateQuery"]));
            }
            set {
                this["MinMaxDateQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\tism_param.ParamInd AS id,\r\n\tism_param.ParamName AS name,\r\n\tism_param.Ed" +
            "_izm AS measure,\r\n\tism_param.ParamOpis AS description\r\nFROM ism_param ORDER BY i" +
            "sm_param.ParamInd")]
        public string SelectMeasuredParameters {
            get {
                return ((string)(this["SelectMeasuredParameters"]));
            }
            set {
                this["SelectMeasuredParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\tfreq_diap.FreqDiapInd AS id, \r\n\tfreq_diap.FreqMin AS min_freq,\r\n\tfreq_d" +
            "iap.FreqMax AS max_freq\r\nFROM freq_diap")]
        public string SelectFreqRanges {
            get {
                return ((string)(this["SelectFreqRanges"]));
            }
            set {
                this["SelectFreqRanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\ttipy_poviv.StruktNum AS id, \r\n\ttipy_poviv.StruktTip AS name,\r\n\ttipy_pov" +
            "iv.ColvoGil AS leads_number\r\nFROM tipy_poviv")]
        public string SelectBendingTypes {
            get {
                return ((string)(this["SelectBendingTypes"]));
            }
            set {
                this["SelectBendingTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\tdr_formuls.DRInd AS id,\r\n\tdr_formuls.DRName AS name,\r\n\tdr_formuls.DROpi" +
            "s AS description\r\nFROM dr_formuls")]
        public string SelectDRFormuls {
            get {
                return ((string)(this["SelectDRFormuls"]));
            }
            set {
                this["SelectDRFormuls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\tdr_priv_formuls.DRPrivInd AS id,\r\n\tdr_priv_formuls.DRPrivName AS name,\r" +
            "\n\tdr_priv_formuls.DRPrivOpis AS description\r\nFROM dr_priv_formuls")]
        public string SelectDRAdductionFormuls {
            get {
                return ((string)(this["SelectDRAdductionFormuls"]));
            }
            set {
                this["SelectDRAdductionFormuls"] = value;
            }
        }
    }
}
